version: "3.8"

services:
  e-front-end:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: e-front-end
    environment:
      - PORT=3002
    ports:
      - 3002:3002
    networks:
      - app_network

networks:
  app_network:
    external: true